services:
  app:
    build: !reset
    environment:
      - CAPYBARA_SAVE_PATH=/opt/app/artifacts
    image: ${DOCKER_APP_IMAGE}
    depends_on:
      selenium:
        condition: service_started
        required: false
    volumes: !override
      - artifacts:/opt/app/artifacts
    secrets:
      - SECRET_KEY_BASE

  db:
    volumes: !reset

  dbeaver: !reset

  init:
    build: !reset
    image: ${DOCKER_APP_IMAGE}
    secrets:
      - SECRET_KEY_BASE
    volumes: !reset

  selenium:
    volumes: !override
      - artifacts:/build

  worker:
    build: !reset
    image: ${DOCKER_APP_IMAGE}
    secrets:
      - SECRET_KEY_BASE
    volumes: !reset

secrets:
  SECRET_KEY_BASE:
    file: /tmp/secret_key_base

volumes:
  artifacts:
