require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/holdings_tasks', type: :request do

  # This should return the minimal set of attributes required to create a valid
  # HoldingsTask. As you add validations to HoldingsTask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      HoldingsTask.create! valid_attributes
      get holdings_tasks_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      holdings_task = HoldingsTask.create! valid_attributes
      get holdings_task_url(holdings_task)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_holdings_task_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      holdings_task = HoldingsTask.create! valid_attributes
      get edit_holdings_task_url(holdings_task)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new HoldingsTask' do
        expect do
          post holdings_tasks_url, params: { holdings_task: valid_attributes }
        end.to change(HoldingsTask, :count).by(1)
      end

      it 'redirects to the created holdings_task' do
        post holdings_tasks_url, params: { holdings_task: valid_attributes }
        expect(response).to redirect_to(holdings_task_url(HoldingsTask.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new HoldingsTask' do
        expect do
          post holdings_tasks_url, params: { holdings_task: invalid_attributes }
        end.to change(HoldingsTask, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post holdings_tasks_url, params: { holdings_task: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested holdings_task' do
        holdings_task = HoldingsTask.create! valid_attributes
        patch holdings_task_url(holdings_task), params: { holdings_task: new_attributes }
        holdings_task.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the holdings_task' do
        holdings_task = HoldingsTask.create! valid_attributes
        patch holdings_task_url(holdings_task), params: { holdings_task: new_attributes }
        holdings_task.reload
        expect(response).to redirect_to(holdings_task_url(holdings_task))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        holdings_task = HoldingsTask.create! valid_attributes
        patch holdings_task_url(holdings_task), params: { holdings_task: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested holdings_task' do
      holdings_task = HoldingsTask.create! valid_attributes
      expect do
        delete holdings_task_url(holdings_task)
      end.to change(HoldingsTask, :count).by(-1)
    end

    it 'redirects to the holdings_tasks list' do
      holdings_task = HoldingsTask.create! valid_attributes
      delete holdings_task_url(holdings_task)
      expect(response).to redirect_to(holdings_tasks_url)
    end
  end
end
