 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lending_items", type: :request do
  
  # LendingItem. As you add validations to LendingItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LendingItem.create! valid_attributes
      get lending_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lending_item = LendingItem.create! valid_attributes
      get lending_item_url(lending_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lending_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      lending_item = LendingItem.create! valid_attributes
      get edit_lending_item_url(lending_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LendingItem" do
        expect {
          post lending_items_url, params: { lending_item: valid_attributes }
        }.to change(LendingItem, :count).by(1)
      end

      it "redirects to the created lending_item" do
        post lending_items_url, params: { lending_item: valid_attributes }
        expect(response).to redirect_to(lending_item_url(LendingItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LendingItem" do
        expect {
          post lending_items_url, params: { lending_item: invalid_attributes }
        }.to change(LendingItem, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post lending_items_url, params: { lending_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lending_item" do
        lending_item = LendingItem.create! valid_attributes
        patch lending_item_url(lending_item), params: { lending_item: new_attributes }
        lending_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lending_item" do
        lending_item = LendingItem.create! valid_attributes
        patch lending_item_url(lending_item), params: { lending_item: new_attributes }
        lending_item.reload
        expect(response).to redirect_to(lending_item_url(lending_item))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        lending_item = LendingItem.create! valid_attributes
        patch lending_item_url(lending_item), params: { lending_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lending_item" do
      lending_item = LendingItem.create! valid_attributes
      expect {
        delete lending_item_url(lending_item)
      }.to change(LendingItem, :count).by(-1)
    end

    it "redirects to the lending_items list" do
      lending_item = LendingItem.create! valid_attributes
      delete lending_item_url(lending_item)
      expect(response).to redirect_to(lending_items_url)
    end
  end
end
