FROM nginx:1.15.1-alpine

COPY conf.d/ /etc/nginx/conf.d/
COPY nginx.conf /etc/nginx/nginx.conf

LABEL edu.berkeley.lib.author1="Daniel C. Schmidt <dcschmidt@berkeley.edu>"
LABEL edu.berkeley.lib.description="Reverse proxy/static file server for altmedia-rails."
LABEL edu.berkeley.lib.maintainer="Daniel C. Schmidt <dcschmidt@berkeley.edu>"
LABEL edu.berkeley.lib.project-url="https://git.lib.berkeley.edu/lap/altmedia"
